name: Next.js CI/CD

on:
  push:
    branches: [main, master]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - name: 🏗 Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: 🏗 Setup Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version-file: package.json
          cache: npm
          check-latest: true

      - name: 📦 Install dependencies
        run: npm ci

      - name: 🧪 Run lint
        run: npm run lint

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    outputs:
      artifact-id: ${{ steps.upload.outputs.artifact-id }}
    steps:
      - name: 🏗 Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: 🏗 Setup Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version-file: package.json
          cache: npm
          check-latest: true

      - name: 📦 Install dependencies
        run: npm ci

      - name: 🏗️ Build
        run: npm run build

      - name: 📦 Upload build artifacts to GitHub
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        id: upload
        with:
          name: out
          if-no-files-found: error
          path: out
          retention-days: 7

  page:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    timeout-minutes: 5
    needs: build
    permissions:
      contents: write
    steps:
      - name: 🏗 Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: 📦 Download page files
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
        id: download
        with:
          artifact-ids: ${{ needs.build.outputs.artifact-id }}
          path: out

      - name: 🏗️ Add .gitignore
        run: cp .gitignore ${{ steps.download.outputs.download-path }}/.gitignore

      - name: 📦 Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@d92aa235d04922e8f08b40ce78cc5442fcfbfa2f # v4
        with:
          folder: ${{ steps.download.outputs.download-path }}
          branch: gh-pages
          clean-exclude: pr-preview
          force: false

  collect:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    name: Final Results
    timeout-minutes: 2
    needs:
      - test
      - build
      - page
    steps:
      - name: ✔️ Fail if any dependency failed
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1
